//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Registers = new HashSet<Register>();
        }
    
        public int Cid { get; set; }
        public string CName { get; set; }
        public int CCapacity { get; set; }
    
        public virtual ICollection<Register> Registers { get; set; }
    }
}
